#pragma once

#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"MARIO GAME"

//#define BACKGROUND_COLOR D3DCOLOR_XRGB(0,0,0)
#define BACKGROUND_COLOR D3DCOLOR_XRGB(156, 252, 240)
#define SCREEN_WIDTH 760
#define SCREEN_HEIGHT 730

#define SCENE_WIDTH 8448
#define SCENE_HEIGHT 1968
#define HEIGHT_HUB 145


#define MAX_FRAME_RATE 120
#define TEX_BLACK_BOARD_ID 40040

#define INTRO_SCENE 4
#define WORLD_MAP 3
#define SCENE_1 1
#define SCENE_2 2